workdir: "../.."

# Define the rule all with all final output files as inputs


rule all:
    input:
        "data/processed/combined_array_standardized.npy",
        "data/processed/session_valid_correct_response.csv"

rule combine_two_arrays:
    input: 
        "data/raw/array1.npy",
        "data/raw/array2.npy"
    output:
        "data/processed/combined_array.npy"
    run:
        import numpy as np
        array1 = np.load(input[0])
        array2 = np.load(input[1])
        data = np.concatenate((array1, array2))
        np.save(output[0], data)

rule standardize_array:
    input:
        "data/processed/combined_array.npy"
    output:
        "data/processed/combined_array_standardized.npy"

    run:
        import numpy as np
        input_array = np.load(input[0])
        output_array = (input_array - np.mean(input_array)) / np.std(input_array)

        np.save(output[0], output_array)

rule normalize_array:
    input:
        "data/processed/combined_array.npy"
    output:
        "data/processed/combined_array_normalized.npy"

    shell:
        'python ../session2/scripts/normalize_array.py {input[0]} {output[0]}'


rule valid_session:
    input:
        "data/raw/session.csv"
    output:
        "data/processed/session_valid.csv" 
    shell:
        'python ../session4/scripts/extract_valid_trials.py {input[0]} {output[0]}'


rule correct_valid_response:
    input:
        "data/processed/session_valid.csv" 
    output:
        "data/processed/session_valid_correct_response.csv"
    
    run:
        import pandas as pd
        df = pd.read_csv(input[0])
        df_correct = df.loc[df['response'] == 1]
        df_correct.to_csv(output[0], index=False)